%let year = 2012;

data newavss;
set newavss.noncalrediecumul;
run;

*prep newavss data and select those during 7/1/2012 and 6/30/2013;
data newavss;
set newavss (rename =(zip = zipchar));
length re $2.;
format dtcreate mmddyy9.;
if ethnicity = 'Hispanic/Latino' then re = 'H';
if ethnicity ^= 'Hispanic/Latino' then do;
	if prxmatch("m/american indian|native american/oi", race) > 0 then re= 'N';	
	if prxmatch("m/bangladesh/oi", race) > 0 then re = 'A';	
	if prxmatch("m/cambodia/oi", race) > 0 then re = 'AB';
	if prxmatch("m/chinese/oi", race) > 0 then re = 'AC';
	if prxmatch("m/filip|fillip|philip|phillip/oi", race) > 0 then re = 'AF';
	if prxmatch("m/hmong/oi", race) > 0 then re = 'A';
	if prxmatch("m/asian india|asian-indian|asian - indian/oi", race) > 0 then race= 'AI';
	if prxmatch("m/indones/oi", race) > 0 then re = 'A';
	if prxmatch("m/japan/oi", race) > 0 then re = 'AJ';
	if prxmatch("m/korea/oi", race) > 0 then re = 'AK';
	if prxmatch("m/laot/oi", race) > 0 then re = 'AL';
	if prxmatch("m/malay/oi", race) > 0 then re = 'A';
	if race in ('ASIAN', 'Asian', 'OTHER ASIAN', 'ASIAN - OTHER', 'ASIAN-OTHER', 'ASIAN - OTHER/UNKNOWN','ASIAN/PACIFIC ISLANDER OTHER','ASIAN/PACIFIC ISLANDER', 'Other Asian/Pac Isl') then re = 'A';
	if prxmatch("m/pakist/oi", race) > 0 then re = 'A';
	if prxmatch("m/singap/oi", race) > 0 then re = 'A';
	if prxmatch("m/taiwan/oi", race) > 0 then re = 'A';
	if prxmatch("m/thai/oi", race) > 0 then re = 'A';
	if prxmatch("m/viet/oi", race) > 0 then re = 'AV';
	if prxmatch("m/black/oi", race) > 0 then re = 'B';
	if prxmatch("m/multi/oi", race) > 0 then re = 'M';
	if race in ('OTHER', 'Other') then re = 'O';
	if prxmatch("m/chamorro/oi", race) > 0 then re = 'AP';
	if prxmatch("m/fiji/oi", race) > 0 then re = 'AP';
	if prxmatch("m/guam/oi", race) > 0 then re = 'AG';
	if prxmatch("m/mashall/oi", race) > 0 then re = 'AP';
	if prxmatch("m/hawaiian/oi", race) > 0 then re = 'AH';
	if race in ('PACIFIC ISLANDER', 'OTHER PACIFIC ISLANDER', 'PACIFIC ISLANDER - OTHER', 'PACIFIC ISLANDER-OTHER', 'PACIFIC ISLANDER - OTHER/UNKNOWN',
				'NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER') then re = 'AP';
	if prxmatch("m/palau/oi", race) > 0 then re = 'AP';
	if prxmatch("m/samoa/oi", race) > 0 then re = 'AS';
	if prxmatch("m/tonga/oi", race) > 0 then re = 'AP';
	if prxmatch("m/yape/oi", race) > 0 then re = 'AP';
	if race in ('UNKNOWN', 'UNK', 'Unknown') then re = 'U';
	if race in ('WHITE', 'White') then re = 'W';
end;
if re = '' then re = 'U';
if xyear = . then xyear = year(dtcreate) - 2000;
year = put(xyear, 2.);
lna = upcase(lna);
fna = upcase(fna);
mna = upcase(mna);
city = upcase(city);
addr = upcase(addr);
ssn = compress(ssn);
zip = input(compress(zipchar), 8.);
rename dtclosed = dup dtcreate = dat;
format dth mmddyy9.;
drop xyear zipchar;
if dis = 'HEP-C-CR';
run;

data newavss;
set newavss;
if dat > mdy(6,30, &year) and dat < mdy(7,1, &year + 1);
run;

data avss.avss_final04112014;
set newavss;
run;

data avss_final;
set newavss;
run;
